name: Commercial Environment Variables Setup
on: 
  workflow_dispatch:
jobs:
  commercial:
    name: Commercial Environment Setup
    runs-on: ubuntu-latest
    env:
      CI_COMMIT_AUTHOR: Continuous Integration
    steps:
      - name: Checkout code from repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Use a specific Python version

      - name: Prepare Environment
        id: prep
        run: /bin/bash .github/workflows./bash/prep.sh

      - name: Set environment variables for additional secrets
        env:
          CORP_TIO_ACCESS_KEY: ${{ secrets.CORP_TENABLE_ACCESS_KEY }}
          CORP_TIO_SECRET_KEY: ${{ secrets.CORP_TENABLE_SECRET_KEY }}

      - name: Git Global Config
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "actions@github.com"
          
